// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AckResolutionReducer from "../ack_resolution_reducer";
import AdvanceTurnPhaseReducer from "../advance_turn_phase_reducer";
import AdvanceWorldReducer from "../advance_world_reducer";
import CheckVictoryReducer from "../check_victory_reducer";
import CommanderDecisionReducer from "../commander_decision_reducer";
import CreateSessionReducer from "../create_session_reducer";
import ExpireTurnReducer from "../expire_turn_reducer";
import FailDeliberationReducer from "../fail_deliberation_reducer";
import FulfillDeliberationReducer from "../fulfill_deliberation_reducer";
import JoinOrResumeSessionReducer from "../join_or_resume_session_reducer";
import RunDeliberationReducer from "../run_deliberation_reducer";
import SeedDemoTurn8Reducer from "../seed_demo_turn_8_reducer";
import SeedDemoWorldReducer from "../seed_demo_world_reducer";
import SetDeliberationModeReducer from "../set_deliberation_mode_reducer";
import SimulateTurnReducer from "../simulate_turn_reducer";
import SubmitTurnReducer from "../submit_turn_reducer";

export type AckResolutionParams = __Infer<typeof AckResolutionReducer>;
export type AdvanceTurnPhaseParams = __Infer<typeof AdvanceTurnPhaseReducer>;
export type AdvanceWorldParams = __Infer<typeof AdvanceWorldReducer>;
export type CheckVictoryParams = __Infer<typeof CheckVictoryReducer>;
export type CommanderDecisionParams = __Infer<typeof CommanderDecisionReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type ExpireTurnParams = __Infer<typeof ExpireTurnReducer>;
export type FailDeliberationParams = __Infer<typeof FailDeliberationReducer>;
export type FulfillDeliberationParams = __Infer<typeof FulfillDeliberationReducer>;
export type JoinOrResumeSessionParams = __Infer<typeof JoinOrResumeSessionReducer>;
export type RunDeliberationParams = __Infer<typeof RunDeliberationReducer>;
export type SeedDemoTurn8Params = __Infer<typeof SeedDemoTurn8Reducer>;
export type SeedDemoWorldParams = __Infer<typeof SeedDemoWorldReducer>;
export type SetDeliberationModeParams = __Infer<typeof SetDeliberationModeReducer>;
export type SimulateTurnParams = __Infer<typeof SimulateTurnReducer>;
export type SubmitTurnParams = __Infer<typeof SubmitTurnReducer>;

