// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  sessionId: __t.u32().name("session_id"),
  name: __t.string(),
  systemTier: __t.string().name("system_tier"),
  commsLagTurns: __t.u32().name("comms_lag_turns"),
  travelTimeTurns: __t.u32().name("travel_time_turns"),
  resourceDeposits: __t.string().name("resource_deposits"),
  position: __t.string(),
});
