// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  sessionId: __t.u32().name("session_id"),
  bodyId: __t.u32().name("body_id"),
  factionId: __t.u32().name("faction_id"),
  name: __t.string(),
  population: __t.u64(),
  infrastructureLevel: __t.u32().name("infrastructure_level"),
  morale: __t.u32(),
  industrialOutput: __t.i32().name("industrial_output"),
  researchOutput: __t.i32().name("research_output"),
  garrisonStrength: __t.i32().name("garrison_strength"),
  supplyStatus: __t.string().name("supply_status"),
  developmentStage: __t.string().name("development_stage"),
});
