// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  factionId: __t.u32().name("faction_id"),
  originCityId: __t.u32().name("origin_city_id"),
  destinationBodyId: __t.u32().name("destination_body_id"),
  manifest: __t.string(),
  departedTurn: __t.u32().name("departed_turn"),
  arrivesTurn: __t.u32().name("arrives_turn"),
  status: __t.string(),
});
