// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  factionId: __t.u32().name("faction_id"),
  turn: __t.u32(),
  fromPersonnelId: __t.u32().name("from_personnel_id"),
  subject: __t.string(),
  body: __t.string(),
  requiresDecision: __t.bool().name("requires_decision"),
  status: __t.string(),
});
