// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  sessionId: __t.u32().name("session_id"),
  playerId: __t.identity().name("player_id"),
  name: __t.string(),
  credits: __t.i32(),
  politicalCapital: __t.i32().name("political_capital"),
  doctrineVector: __t.string().name("doctrine_vector"),
  controlScore: __t.i32().name("control_score"),
  readyForTurn: __t.bool().name("ready_for_turn"),
});
