// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  state: __t.string(),
  currentYear: __t.u32().name("current_year"),
  currentTurn: __t.u32().name("current_turn"),
  playerAFactionId: __t.option(__t.u32()).name("player_a_faction_id"),
  playerBFactionId: __t.option(__t.u32()).name("player_b_faction_id"),
  turnPhase: __t.string().name("turn_phase"),
  turnDeadline: __t.option(__t.timestamp()).name("turn_deadline"),
  winnerFactionId: __t.option(__t.u32()).name("winner_faction_id"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
