// AUTO-GENERATED by `npm run generate` from repo root.
// Re-run after schema changes in server/src/module.ts.
// Do not edit manually — this file will be overwritten on next generate.
//
// Current state: empty module scaffold (P1E1). Tables and reducers
// are added in P1E2+. Re-generate after each schema change.

export {
  DbConnectionImpl,
  DbConnectionBuilder,
  type DbConnectionConfig,
} from 'spacetimedb';

// Typed as empty until tables and reducers are defined.
export type RemoteTables = Record<never, never>;
export type RemoteReducers = Record<never, never>;

export const tables: RemoteTables = {};
export const reducers: RemoteReducers = {};
