// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  sessionId: __t.u32().name("session_id"),
  factionId: __t.u32().name("faction_id"),
  requestType: __t.string().name("request_type"),
  contextJson: __t.string().name("context_json"),
  status: __t.string(),
  responseJson: __t.option(__t.string()).name("response_json"),
  error: __t.option(__t.string()),
  errorCode: __t.option(__t.string()).name("error_code"),
  attemptCount: __t.u32().name("attempt_count"),
  createdTurn: __t.u32().name("created_turn"),
  updatedTurn: __t.u32().name("updated_turn"),
});
