// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  factionId: __t.u32().name("faction_id"),
  name: __t.string(),
  role: __t.string(),
  department: __t.string(),
  postingCityId: __t.option(__t.u32()).name("posting_city_id"),
  competence: __t.u32(),
  creativity: __t.u32(),
  reliability: __t.u32(),
  ambition: __t.u32(),
  politicalSkill: __t.u32().name("political_skill"),
  communication: __t.u32(),
  loyalty: __t.u32(),
  autonomyTolerance: __t.u32().name("autonomy_tolerance"),
  morale: __t.u32(),
  burnout: __t.u32(),
  salary: __t.i32(),
});
