// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  factionId: __t.u32().name("faction_id"),
  cityId: __t.u32().name("city_id"),
  type: __t.string(),
  name: __t.string(),
  progress: __t.i32(),
  resourcesAssigned: __t.i32().name("resources_assigned"),
  estCompletion: __t.u32().name("est_completion"),
  status: __t.string(),
});
