// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  sessionId: __t.u32().name("session_id"),
  factionId: __t.u32().name("faction_id"),
  turn: __t.u32(),
  summaryJson: __t.string().name("summary_json"),
  narrativeJson: __t.option(__t.string()).name("narrative_json"),
  acknowledged: __t.bool(),
  acknowledgedAt: __t.option(__t.timestamp()).name("acknowledged_at"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
