// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CelestialBodies = __t.object("CelestialBodies", {
  id: __t.u32(),
  sessionId: __t.u32(),
  name: __t.string(),
  systemTier: __t.string(),
  commsLagTurns: __t.u32(),
  travelTimeTurns: __t.u32(),
  resourceDeposits: __t.string(),
  position: __t.string(),
});
export type CelestialBodies = __Infer<typeof CelestialBodies>;

export const Cities = __t.object("Cities", {
  id: __t.u32(),
  sessionId: __t.u32(),
  bodyId: __t.u32(),
  factionId: __t.u32(),
  name: __t.string(),
  population: __t.u64(),
  infrastructureLevel: __t.u32(),
  morale: __t.u32(),
  industrialOutput: __t.i32(),
  researchOutput: __t.i32(),
  garrisonStrength: __t.i32(),
  supplyStatus: __t.string(),
  developmentStage: __t.string(),
});
export type Cities = __Infer<typeof Cities>;

export const ColonyShips = __t.object("ColonyShips", {
  id: __t.u32(),
  factionId: __t.u32(),
  originCityId: __t.u32(),
  destinationBodyId: __t.u32(),
  manifest: __t.string(),
  departedTurn: __t.u32(),
  arrivesTurn: __t.u32(),
  status: __t.string(),
});
export type ColonyShips = __Infer<typeof ColonyShips>;

export const CommanderInbox = __t.object("CommanderInbox", {
  id: __t.u32(),
  factionId: __t.u32(),
  turn: __t.u32(),
  fromPersonnelId: __t.u32(),
  subject: __t.string(),
  body: __t.string(),
  requiresDecision: __t.bool(),
  status: __t.string(),
});
export type CommanderInbox = __Infer<typeof CommanderInbox>;

export const Events = __t.object("Events", {
  id: __t.u32(),
  sessionId: __t.u32(),
  factionId: __t.option(__t.u32()),
  turn: __t.u32(),
  eventType: __t.string(),
  payload: __t.string(),
});
export type Events = __Infer<typeof Events>;

export const Factions = __t.object("Factions", {
  id: __t.u32(),
  sessionId: __t.u32(),
  playerId: __t.identity(),
  name: __t.string(),
  credits: __t.i32(),
  politicalCapital: __t.i32(),
  doctrineVector: __t.string(),
  controlScore: __t.i32(),
  readyForTurn: __t.bool(),
});
export type Factions = __Infer<typeof Factions>;

export const Fleets = __t.object("Fleets", {
  id: __t.u32(),
  factionId: __t.u32(),
  postingCityId: __t.u32(),
  strength: __t.i32(),
  orders: __t.option(__t.string()),
});
export type Fleets = __Infer<typeof Fleets>;

export const GameSessions = __t.object("GameSessions", {
  id: __t.u32(),
  state: __t.string(),
  currentYear: __t.u32(),
  currentTurn: __t.u32(),
  playerAFactionId: __t.option(__t.u32()),
  playerBFactionId: __t.option(__t.u32()),
  turnPhase: __t.string(),
  turnDeadline: __t.option(__t.timestamp()),
  winnerFactionId: __t.option(__t.u32()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type GameSessions = __Infer<typeof GameSessions>;

export const IntelligenceRecords = __t.object("IntelligenceRecords", {
  id: __t.u32(),
  observerFactionId: __t.u32(),
  targetFactionId: __t.u32(),
  intelType: __t.string(),
  value: __t.string(),
  accuracy: __t.i32(),
  acquiredTurn: __t.u32(),
});
export type IntelligenceRecords = __Infer<typeof IntelligenceRecords>;

export const LlmRequests = __t.object("LlmRequests", {
  id: __t.u32(),
  sessionId: __t.u32(),
  factionId: __t.u32(),
  requestType: __t.string(),
  contextJson: __t.string(),
  status: __t.string(),
  responseJson: __t.option(__t.string()),
  error: __t.option(__t.string()),
  createdTurn: __t.u32(),
});
export type LlmRequests = __Infer<typeof LlmRequests>;

export const Personnel = __t.object("Personnel", {
  id: __t.u32(),
  factionId: __t.u32(),
  name: __t.string(),
  role: __t.string(),
  department: __t.string(),
  postingCityId: __t.option(__t.u32()),
  competence: __t.u32(),
  creativity: __t.u32(),
  reliability: __t.u32(),
  ambition: __t.u32(),
  politicalSkill: __t.u32(),
  communication: __t.u32(),
  loyalty: __t.u32(),
  autonomyTolerance: __t.u32(),
  morale: __t.u32(),
  burnout: __t.u32(),
  salary: __t.i32(),
});
export type Personnel = __Infer<typeof Personnel>;

export const PersonnelRelationships = __t.object("PersonnelRelationships", {
  id: __t.u32(),
  personnelAId: __t.u32(),
  personnelBId: __t.u32(),
  type: __t.string(),
  strength: __t.i32(),
});
export type PersonnelRelationships = __Infer<typeof PersonnelRelationships>;

export const Projects = __t.object("Projects", {
  id: __t.u32(),
  factionId: __t.u32(),
  cityId: __t.u32(),
  type: __t.string(),
  name: __t.string(),
  progress: __t.i32(),
  resourcesAssigned: __t.i32(),
  estCompletion: __t.u32(),
  status: __t.string(),
});
export type Projects = __Infer<typeof Projects>;

export const Proposals = __t.object("Proposals", {
  id: __t.u32(),
  factionId: __t.u32(),
  turn: __t.u32(),
  proposingPersonnelId: __t.u32(),
  department: __t.string(),
  title: __t.string(),
  body: __t.string(),
  resourceCost: __t.i32(),
  confidence: __t.string(),
  status: __t.string(),
  decision: __t.option(__t.string()),
});
export type Proposals = __Infer<typeof Proposals>;

export const TradeAgreements = __t.object("TradeAgreements", {
  id: __t.u32(),
  sessionId: __t.u32(),
  factionAId: __t.u32(),
  factionBId: __t.u32(),
  terms: __t.string(),
  signedTurn: __t.u32(),
  expiresTurn: __t.option(__t.u32()),
});
export type TradeAgreements = __Infer<typeof TradeAgreements>;
